//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainProject.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainProject.res.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af,Afrikaans,,ZA
        ///﻿af-ZA,Afrikaans,South Africa,ZA
        ///sq,Albanian,,AL
        ///sq-AL,Albanian,Albania,AL
        ///ar,Arabic,,AE
        ///ar-DZ,Arabic,Algeria,DZ
        ///ar-BH,Arabic,Bahrain,BH
        ///ar-EG,Arabic,Egypt,EG
        ///ar-IQ,Arabic,Iraq,IQ
        ///ar-JO,Arabic,Jordan,JO
        ///ar-KW,Arabic,Kuwait,KW
        ///ar-LB,Arabic,Lebanon,LB
        ///ar-LY,Arabic,Libya,LY
        ///ar-MA,Arabic,Morocco,MA
        ///ar-OM,Arabic,Oman,OM
        ///ar-QA,Arabic,Qatar,QA
        ///ar-SA,Arabic,Saudi Arabia,SA
        ///ar-SY,Arabic,Syria,SY
        ///ar-TN,Arabic,Tunisia,TN
        ///ar-AE,Arabic,United Arab Emirates,AE
        ///ar-YE,Arabic,Yemen,YE
        ///h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cultures {
            get {
                return ResourceManager.GetString("cultures", resourceCulture);
            }
        }
    }
}
